# ADHD 生產力系統 - Prometheus 監控配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'adhd-productivity-monitor'

# 規則檔案
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 監控目標配置
scrape_configs:
  # Prometheus 自我監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # ADHD 後端 API 監控
  - job_name: 'adhd-backend'
    static_configs:
      - targets: ['adhd-backend:5000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # ADHD 前端應用監控
  - job_name: 'adhd-frontend'
    static_configs:
      - targets: ['adhd-frontend:3000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL 資料庫監控 (如果有 postgres_exporter)
  - job_name: 'adhd-postgres'
    static_configs:
      - targets: ['adhd-postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis 快取監控 (如果有 redis_exporter)
  - job_name: 'adhd-redis'
    static_configs:
      - targets: ['adhd-redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx 反向代理監控
  - job_name: 'adhd-nginx'
    static_configs:
      - targets: ['adhd-nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker 容器監控 (如果有 cadvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # 節點監控 (如果有 node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

# 警報管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 遠程寫入配置 (可選)
# remote_write:
#   - url: "http://remote-storage:9201/write"

# 遠程讀取配置 (可選)
# remote_read:
#   - url: "http://remote-storage:9201/read"